version: '3'
services:
  app:
    build:
      context: .
    container_name: coin-inspector-app
    ports:
      - "${PORT:-5173}:${PORT:-5173}"
    volumes:
      - .:/app
      - /app/node_modules
      - ./.env:/app/.env
    command: npm run dev
